---
- import_tasks: power_down_node.yml
  when: power_state == 'halt'
  become: yes

- import_tasks: restart_nodes.yml
  when: power_state == 'reboot'
  become: yes

- import_tasks: power_on_node.yml
  when: power_state == 'running'
  become: yes
