# playbook to powerup node
- name: Powering up master
  command: virsh start master
  become: yes
  ignore_errors: true
  delegate_to:  localhost
  when:
    - power_state == "running"
- name: Wait 320 seconds, but only start checking after 30 seconds
  wait_for_connection:
    delay: 30
    timeout: 320
  when:
    - power_state  == "running"
  delegate_to:  "{{ master_node }}"
- name: Power up infra nodes "{{ item }}"
  block:
  - name: Powering up node
    command: virsh start {{ item }}
    become: yes
    ignore_errors: true
    delegate_to:  localhost
    when:
      - power_state == "running"
    with_items:
      - "{{ infra_nodes }}"
  - name: Wait 320 seconds, but only start checking after 30 seconds
    wait_for_connection:
      delay: 30
      timeout: 320
    when:
      - power_state  == "running"
    delegate_to: "{{ item }}"
    with_items:
      - "{{ fqdn_infra_names }}"
  - name: Create ocp-power-management.log file.
    file:
      path: "/var/log/ocp-power-management.log"
      state: touch
      mode: 0777
      owner: root
    become: true
  - name: Run script check_system_state.sh the remote node
    script: files/check_system_state.sh infra | tee /var/log/ocp-power-management.log
    become: true
    when:
      - power_state  == "running"
- name: Power up compute nodes "{{ item }}"
  block:
  - name: Powering up node
    command: virsh start {{ item }}
    become: yes
    ignore_errors: true
    delegate_to: localhost
    when:
      - power_state == "running"
    with_items:
      - "{{ compute_nodes }}"
  - name: Wait 320 seconds, but only start checking after 30 seconds
    wait_for_connection:
      delay: 30
      timeout: 320
    when:
      - power_state  == "running"
    delegate_to: "{{ item }}"
    with_items:
      - "{{ fqdn_compute_names }}"
  - name: Run script check_system_state.sh the remote node
    script: files/check_system_state.sh compute | tee /var/log/ocp-power-management.log
    become: true
    when:
      - power_state  == "running"
