# playbook to powerup node
- name: Power up infra nodes "{{ item }}"
  block:
  - name: Powering up node
    shell: virsh start {{ item }}
    become: yes
    delegate_to:  localhost
    when:
      -  power_state == "running"
  - name: Wait 60 seconds, but only start checking after 30 seconds
    wait_for_connection:
      delay: 30
      timeout: 60
    when:
      - power_state  == "running"
    delegate_to: "{{ item }}"
      - name: Run a script only if file.txt exists on the remote node
        script: files/check_system_state.sh infra | tee /var/log/ocp-power-mnanagement.log
        when:
          - power_state  == "running"
  with_items:
    - "{{ infra_nodes }}"
- name: Power up compute nodes "{{ item }}"
  block:
  - name: Powering up node
    shell: virsh start {{ item }}
    become: yes
    delegate_to:  localhost
    when:
      -  power_state == "running"
  - name: Wait 60 seconds, but only start checking after 30 seconds
    wait_for_connection:
      delay: 30
      timeout: 60
    when:
      - power_state  == "running"
    delegate_to: "{{ item }}"
      - name: Run a script only if file.txt exists on the remote node
        script: files/check_system_state.sh compute | tee /var/log/ocp-power-mnanagement.log
        when:
          - power_state  == "running"
  with_items:
    - "{{ compute_nodes }}"
