# Setting the node to NOT schedulable draining the node then restarting
- name: get variables
  debug: var=compute_node_single

- name: Setting {{ fqdn_compute_node_single }} to unschedulable
  block:
  - name: Setting the {{ fqdn_compute_node_single }} to NOT schedulable
    shell: |
      echo "NODE: {{ fqdn_compute_node_single }}"
      oc adm manage-node "{{ fqdn_compute_node_single }}" --schedulable=false
  - name:  Drain Containers running on node
    shell: |
      oc adm drain "{{ fqdn_compute_node_single }}" --grace-period=180 --timeout=0
    ignore_errors: yes
- name: Restarting compute nodes {{ compute_node_single }}
  block:
  - name: "reboot {{ compute_node_single }}"
    shell: sleep 2 && shutdown -r now "Restarting node"
    async: 1
    poll: 0
    ignore_errors: true
    become: true
    delegate_to: "{{ compute_node_single }}"
    when:
      -  power_state  == "reboot"
  - name: Wait 320 seconds, but only start checking after 180 seconds
    wait_for_connection:
      delay: 180
      timeout: 320
    when:
      - power_state  == "reboot"
    delegate_to: "{{ compute_node_single }}"
  - name: Run a script only if file.txt exists on the remote node
    script: files/check_system_state.sh both | tee /var/log/ocp-power-mnanagement.log
    when:
      - power_state  == "reboot"
